name: 'qs-github-release'
description: 'GitHub Release Package'
author: 'Qernal (https://qernal.com/)'
branding:
  icon: download
  color: purple

inputs:
  tag:
    description: Tag to create for this release (usually the version)
    required: true
  tag_pattern:
    description: The pattern of the tag to use
    required: false
  release_name:
    description: Name of this release
    required: false
  release_description:
    description: Release description
    required: false
  prerelease:
    description: Set the release to be a prelease type (non-stable release)
    required: false
  repo_name:
    description: Name of the repository to create release on
    required: true
  assets:
    description: List of assets to release
    required: true
  auto_increment:
    description: Auto increment the semver on the last tag found
    required: false
  dry_run:
    description: Dry run the release, useful for non-release branches
    required: false
  token:
    description: GitHub PAT Token to access/create release
    required: true
  get_last_tag:
    description: Gets the last tag that was created, doesn't create or update the release - this is for information
    required: false
outputs:
  tag:
    description: Tag that was created during the release

runs:
  using: 'docker'
  image: 'docker://ghcr.io/qernal/gh-actions/release-x86_64:v1.0.4'